# The `modules` picks up every blueprint in `site/blueprints/modules/`.

title: Default Page
tabs:
  content:
    sections:
      modules:
        default: text
  files:
    sections:
      files: true
