# You'll want to define which templates users can create
# by using `create`, `templates` or `templatesIgnore`,
# otherwise your modules will show up here, too.

title: Site

sections:
  pages:
    type: pages
    create: default
